//
//  AppDelegate.m
//  AppDatabaseGenerator
//
//  Created by Anthony Mittaz on 7/02/09.
//  Copyright 2009 Anthony Mittaz. All rights reserved.
//
//  This sourcecode is released under the Apache License, Version 2.0
//  http://www.apache.org/licenses/LICENSE-2.0.html
//  
//


#import "AppDelegate.h"
#import "FmdbMigrationManager.h"
#import "InitialUserTables.h"
#import "SBJSON.h"


@implementation AppDelegate

@synthesize userdb=_userdb;

- (id)init {
	if (self = [super init]) {
	}
	return self;
}

- (void)applicationDidFinishLaunching:(NSNotification *)aNotification
{	
	[self loadUserDatabase:self];
	
	[self fillDatabaseByIncludingAustralianList:TRUE forState:@"ACT" andSuburbs:@"SHOW ALL,AINSLIE,BANKS,BARTON,BELCONNEN,BONYTHON,BRADDON,BRUCE,CALWELL,CAMPBELL,CANBERRA,CHIFLEY,CHISHOLM,CITY,CONDER,CURTIN,DICKSON,DOWNER,EVATT,FADDEN,FARRER,FLOREY,FORREST,FRASER,GORDON,GREENWAY,GRIFFITH,GUNGAHLIN,HACKETT,HAWKER,HOLT,HUGHES,ISAACS,ISABELLA PLAINS,KALEEN,KAMBAH,KINGSTON,LATHAM,LYNEHAM,LYONS,MACQUARIE,MAWSON,MCKELLAR,MONASH,NARRABUNDAH,NGUNNAWAL,NICHOLLS,O'CONNOR,OXLEY,PAGE,PALMERSTON,PEARCE,PHILLIP,RIVETT,STIRLING,THARWA,THEODORE,TURNER,WANNIASSA,WARAMANGA,WATSON,WESTON,YARRALUMLA"];
	[self fillDatabaseByIncludingAustralianList:TRUE forState:@"NSW" andSuburbs:@"SHOW ALL,ABBOTSBURY,ABBOTSFORD,ABERDARE,ABERDEEN,ABERGLASSLYN,ACACIA GARDENS,ADAMSTOWN,AGNES BANKS,ALBION PARK,ALBION PARK RAIL,ALBURY,ALEXANDRIA,ALFORDS POINT,ALLAMBIE,ALLAMBIE HEIGHTS,ALLAWAH,ALSTONVILLE,AMBARVALE,ANGOURIE,ANNA BAY,ANNANDALE,ANNANGROVE,APPIN,ARCADIA,ARCADIA VALE,ARDLETHAN,ARMIDALE,ARNCLIFFE,ARTARMON,ASHBURY,ASHCROFT,ASHFIELD,ASHMONT,ASHTONFIELD,ASQUITH,AUBURN,AUSTINMER,AUSTRAL,AVALON,AVOCA BEACH,AWABA,BACK CREEK,BALCOLYN,BALGOWLAH,BALGOWLAH HEIGHTS,BALGOWNIE,BALLINA,BALMAIN,BALMAIN EAST,BALMORAL,BALMORAL VILLAGE,BANGALOW,BANGOR,BANKSIA,BANKSTOWN,BANORA POINT,BAR BEACH,BAR POINT,BARDEN RIDGE,BARDWELL PARK,BARELLAN,BARGO,BARNSLEY,BAROOGA,BARRACK HEIGHTS,BASIN VIEW,BASS HILL,BATEAU BAY,BATEHAVEN,BATEMANS BAY,BATHURST,BATLOW,BAULKHAM HILLS,BAYVIEW,BEACON HILL,BEACONSFIELD,BEAUMONT,BEAUMONT HILLS,BEAUTY POINT,BEECROFT,BELFIELD,BELLA VISTA,BELLAMBI,BELLBIRD,BELLBROOK,BELLEVUE HILL,BELLINGEN,BELMONT,BELMONT NORTH,BELMORE,BELROSE,BENDEMEER,BENEREMBAH,BENSVILLE,BERALA,BERESFIELD,BERKELEY,BERKELEY VALE,BERKSHIRE PARK,BERMAGUI,BEROWRA,BEROWRA HEIGHTS,BEROWRA WATERS,BERRIDALE,BERRIMA,BERRY,BEVERLEY PARK,BEVERLY HILLS,BEXLEY,BEXLEY NORTH,BIDWILL,BIG HILL,BILAMBIL,BILAMBIL HEIGHTS,BILGOLA,BILGOLA PLATEAU,BILPIN,BIRCHGROVE,BIRMINGHAM GARDENS,BIRRONG,BLACKALLS PARK,BLACKBUTT,BLACKETT,BLACKHEATH,BLACKSMITHS,BLACKTOWN,BLACKWALL,BLAIR ATHOL,BLAKEHURST,BLAXLAND,BLAXLAND EAST,BLAYNEY,BLIGH PARK,BLUE BAY,BLUE HAVEN,BOAMBEE,BOAMBEE EAST,BOAT HARBOUR,BOGANGAR,BOGGABRI,BOLTON POINT,BOLWARRA,BOMADERRY,BONDI,BONDI BEACH,BONDI JUNCTION,BONNELLS BAY,BONNET BAY,BONNYRIGG,BONNYRIGG HEIGHTS,BOOKER BAY,BOOLAROO,BOOMERANG BEACH,BOORABEE PARK,BOORAGUL,BOSSLEY PARK,BOTANY,BOURKELANDS,BOW BOWING,BOWEN MOUNTAIN,BOWRAL,BOWRAVILLE,BOX HILL,BRADBURY,BRANXTON,BREAKFAST POINT,BREDBO,BREWONGLE,BRIGHTON LE SANDS,BRIGHTWATERS,BRINGELLY,BROADMEADOW,BROADWATER,BROADWAY,BROKE,BROKEN HILL,BRONTE,BROOKVALE,BRUNSWICK HEADS,BUDGEWOI,BUFF POINT,BULGA,BULLABURRA,BULLI,BUNDANOON,BUNDEENA,BUNGENDORE,BUNGONIA,BUNGOWANNAH,BURONGA,BURRADOO,BURRAWANG,BURRILL LAKE,BURRINGBAR,BURRUMBUTTOCK,BURWOOD,BUSBY,BUTTABA,BUTTERWICK,BUXTON,BYRON BAY,CABARITA,CABARITA BEACH,CABRAMATTA,CABRAMATTA WEST,CALALA,CALGA,CALLALA BAY,CALLALA BEACH,CAMBRIDGE PARK,CAMDEN,CAMDEN SOUTH,CAMERON PARK,CAMMERAY,CAMPBELLTOWN,CAMPERDOWN,CAMPSIE,CAMS WHARF,CANADA BAY,CANIABA,CANLEY HEIGHTS,CANLEY VALE,CANOELANDS,CANTERBURY,CANTON BEACH,CANYONLEIGH,CARDIFF,CARDIFF SOUTH,CAREY BAY,CARINGBAH,CARLINGFORD,CARLTON,CARNES HILL,CARRAMAR,CARRINGTON,CARROLL,CASINO,CASTLE COVE,CASTLE HILL,CASTLECRAG,CASTLEREAGH,CASUARINA,CASULA,CATALINA,CATHERINE FIELD,CATHERINE HILL BAY,CAVES BEACH,CECIL HILLS,CENTENNIAL PARK,CESSNOCK,CHAIN VALLEY BAY,CHARLESTOWN,CHARMHAVEN,CHATHAM,CHATSWOOD,CHATSWOOD WEST,CHELTENHAM,CHERRYBROOK,CHESTER HILL,CHIFLEY,CHILCOTTS GRASS,CHILLINGHAM,CHINDERAH,CHIPPENDALE,CHIPPING NORTON,CHISWICK,CHITTAWAY BAY,CHITTAWAY POINT,CHURCH POINT,CIRCULAR QUAY,CLAREMONT MEADOWS,CLAREVILLE,CLONTARF,CLOVELLY,CLUNES,COAL POINT,COBAR,COBBITTY,COFFS HARBOUR,COFFS HARBOUR JETTY,COLEAMBALLY,COLEDALE,COLINTON,COLLAROY,COLLAROY BEACH,COLLAROY PLATEAU,COLO VALE,COLYTON,COMO,CONCORD,CONCORD WEST,CONDELL PARK,CONISTON,CONNELLS POINT,CONSTITUTION HILL,COOGEE,COOKS HILL,COOLAMON,COOLANGATTA,COOLONGOLOOK,COOMA,COOMBA PARK,COORANBONG,COPACABANA,CORAKI,CORAMBA,CORDEAUX HEIGHTS,CORINDI BEACH,CORLETTE,COROWA,CORRIMAL,CORRIMAL EAST,COUTTS CROSSING,COWRA,CRANEBROOK,CREMORNE,CREMORNE POINT,CRINGILA,CROMER,CRONULLA,CROOKWELL,CROWS NEST,CROYDON,CROYDON PARK,CUDGEN,CULBURRA BEACH,CUNDLETOWN,CURL CURL,CURLWAA,CURRANS HILL,DACEYVILLE,DALEYS POINT,DANGAR ISLAND,DAPTO,DARETON,DARLING HARBOUR,DARLING ISLAND,DARLING POINT,DARLINGHURST,DARLINGTON,DARLINGTON POINT,DAVIDSON,DAVISTOWN,DEAN PARK,DEE WHY,DENILIQUIN,DENISTONE,DENISTONE EAST,DENISTONE WEST,DENMAN,DHARRUK,DIAMOND BAY,DIAMOND BEACH,DOLANS BAY,DOLLS POINT,DOONSIDE,DORA CREEK,DOUBLE BAY,DOUGLAS PARK,DOVER HEIGHTS,DOYALSON,DRUMMOYNE,DUBBO,DUDLEY,DULWICH HILL,DUNBOGAN,DUNDAS,DUNGOG,DURAL,EAGLE VALE,EARLWOOD,EAST ALBURY,EAST BALLINA,EAST GOSFORD,EAST HILLS,EAST JINDABYNE,EAST KEMPSEY,EAST KURRAJONG,EAST LINDFIELD,EAST LISMORE,EAST MAITLAND,EAST RYDE,EAST TAMWORTH,EAST WARDELL,EASTERN CREEK,EASTLAKES,EASTWOOD,EBENEZER,EDENSOR PARK,EDGECLIFF,EDGEWORTH,EGLINTON,ELANORA HEIGHTS,ELEEBANA,ELERMORE VALE,ELIZABETH BAY,ELIZABETH BEACH,ELRINGTON,EMERALD BEACH,EMERTON,EMU HEIGHTS,EMU PLAINS,ENFIELD,ENGADINE,ENMORE,EPPING,ERINA,ERMINGTON,EROWAL BAY,ERSKINE PARK,ERSKINEVILLE,ESCHOL PARK,ESTELLA,ETTALONG BEACH,EUNGAI CREEK,EURONGILLY,EVANS HEAD,EWINGSDALE,EXETER,FAIRFIELD,FAIRFIELD EAST,FAIRFIELD HEIGHTS,FAIRFIELD WEST,FAIRLIGHT,FAIRY MEADOW,FARMBOROUGH HEIGHTS,FAULCONBRIDGE,FENNELL BAY,FIGTREE,FINGAL BAY,FINGAL HEAD,FISHERMANS PARADISE,FISHERMANS REACH,FISHING POINT,FIVE DOCK,FLINDERS,FLORAVILLE,FORBES,FOREST HILL,FOREST LODGE,FORESTVILLE,FORRESTERS BEACH,FORSTER,FOUNTAINDALE,FREEMANS REACH,FRENCHS FOREST,GALSTON,GARDEN SUBURB,GATESHEAD,GEORGES HALL,GEORGETOWN,GERRINGONG,GERROA,GEURIE,GILLIESTON HEIGHTS,GIRRAWEEN,GLADESVILLE,GLEBE,GLEN ALPINE,GLEN INNES,GLEN OAK,GLENBROOK,GLENDALE,GLENDENNING,GLENFIELD,GLENFIELD PARK,GLENHAVEN,GLENMORE PARK,GLENNING VALLEY,GLENORIE,GLENWOOD,GLOSSODIA,GLOUCESTER,GOL GOL,GOOLGOWI,GOONELLABAH,GORDON,GOROKAN,GOSFORD,GOSFORD WEST,GOULBURN,GRAFTON,GRANVILLE,GRATTAI,GRAYS POINT,GREEN POINT,GREEN VALLEY,GREENACRE,GREENFIELD PARK,GREENWELL POINT,GREENWICH,GRENFELL,GRETA,GREYSTANES,GRIFFITH,GUILDFORD,GUILDFORD WEST,GULGONG,GUNDAGAI,GUNDAROO,GUNNEDAH,GUNNING,GUYRA,GWANDALAN,GWYNNEVILLE,GYMEA,GYMEA BAY,HABERFIELD,HALEKULANI,HALLIDAYS POINT,HAMILTON,HAMILTON EAST,HAMILTON NORTH,HAMILTON SOUTH,HAMLYN TERRACE,HAMMONDVILLE,HANWOOD,HARBORD,HARRINGTON,HARRINGTON PARK,HARRIS PARK,HASSALL GROVE,HASTINGS POINT,HAT HEAD,HAWKS NEST,HAY,HAYMARKET,HAZELBROOK,HEATHCOTE,HEBERSHAM,HECKENBERG,HELENSBURGH,HENTY,HILL TOP,HILLSDALE,HILLSTON,HINCHINBROOK,HOBARTVILLE,HOLROYD,HOLSWORTHY,HOMEBUSH,HOMEBUSH BAY,HOMEBUSH WEST,HORNINGSEA PARK,HORNSBY,HORNSBY HEIGHTS,HORSFIELD BAY,HORSLEY,HORSLEY PARK,HOWLONG,HOXTON PARK,HUNTERS HILL,HUNTLEYS COVE,HURLSTONE PARK,HURSTVILLE,HURSTVILLE GROVE,HUSKISSON,HYLAND PARK,ILLAWONG,INGLEBURN,INGLESIDE,ISLINGTON,JAMISONTOWN,JANNALI,JERRABOMBERRA,JERRYS PLAINS,JESMOND,JILLIBY,JINDABYNE,JINDERA,JUNEE,KAHIBAH,KANAHOOKA,KANGAROO VALLEY,KANWAL,KAREELA,KARIONG,KARUAH,KATOOMBA,KEARNS,KEIRAVILLE,KELLYVILLE,KELLYVILLE RIDGE,KELSO,KEMBLAWARRA,KEMPS CREEK,KEMPSEY,KENDALL,KENSINGTON,KENTHURST,KIAMA,KIAMA DOWNS,KIAMA HEIGHTS,KILABEN BAY,KILLARA,KILLARNEY HEIGHTS,KILLARNEY VALE,KILLCARE,KILLCARE HEIGHTS,KINCUMBER,KINCUMBER SOUTH,KINGS CROSS,KINGS LANGLEY,KINGS PARK,KINGSCLIFF,KINGSFORD,KINGSGROVE,KINGSVALE,KINGSWOOD,KIOLOA,KIRRAWEE,KIRRIBILLI,KITCHENER,KOGARAH,KOGARAH BAY,KOOLEWONG,KOONAWARRA,KOORAWATHA,KOORINGAL,KOOTINGAL,KORORA,KOTARA,KURMOND,KURNELL,KURRAJONG HEIGHTS,KURRAJONG HILLS,KURRI KURRI,KYEEMAGH,KYLE BAY,KYOGLE,LA PEROUSE,LAGUNA,LAKE ALBERT,LAKE CATHIE,LAKE HAVEN,LAKE HEIGHTS,LAKE ILLAWARRA,LAKE MUNMORAH,LAKELANDS,LAKEMBA,LALOR PARK,LAMBTON,LANE COVE,LANSVALE,LAPSTONE,LARGS,LAURIETON,LAVENDER BAY,LAVINGTON,LAWSON,LEETON,LEICHHARDT,LEMON TREE PASSAGE,LENNOX HEAD,LEONAY,LEPPINGTON,LETHBRIDGE PARK,LEUMEAH,LEURA,LEWISHAM,LIBERTY GROVE,LIDCOMBE,LIDSDALE,LILLI PILLI,LILYFIELD,LINDFIELD,LISAROW,LISMORE,LISMORE HEIGHTS,LITHGOW,LITTLE BAY,LIVERPOOL,LOCHINVAR,LOCKHART,LOFTUS,LONDONDERRY,LONG JETTY,LONGUEVILLE,LOOMBERAH,LORN,LOWER PORTLAND,LUCKNOW,LURNEA,MACKSVILLE,MACQUARIE FIELDS,MACQUARIE HILLS,MACQUARIE LINKS,MACQUARIE PARK,MAIANBAR,MAITLAND,MALABAR,MALONEYS BEACH,MANGERTON,MANLY,MANLY VALE,MANNERING PARK,MANYANA,MARAYLYA,MARAYONG,MARDI,MARKS POINT,MARMONG POINT,MAROM CREEK,MAROUBRA,MAROUBRA JUNCTION,MARRANGAROO,MARRICKVILLE,MARSDEN PARK,MARSFIELD,MARTINSVILLE,MARULAN,MARYLAND,MARYVILLE,MASCOT,MATCHAM,MATRAVILLE,MAYFIELD,MAYS HILL,MCGRATHS HILL,MCKEES HILL,MCLEANS RIDGES,MCMAHONS POINT,MEADOWBANK,MEDLOW BATH,MEDOWIE,MELROSE PARK,MENAI,MENANGLE,MEREWETHER,MEREWETHER HEIGHTS,MERIMBULA,MERRYLANDS,METFORD,MICHELAGO,MIDDLE DURAL,MILLER,MILLERS POINT,MILPERRA,MILSONS POINT,MINCHINBURY,MINNAMURRA,MINNIE WATER,MINTO,MINTO HEIGHTS,MIRANDA,MIRRABOOKA,MITTAGONG,MOAMA,MOLLYMOOK,MOLONG,MONA VALE,MONTEREY,MOONEE BEACH,MOORE PARK,MOOREBANK,MORISSET,MORPETH,MORTDALE,MORTLAKE,MORUYA,MORUYA HEADS,MOSMAN,MOSS VALE,MOUNT ANNAN,MOUNT AUSTIN,MOUNT COLAH,MOUNT DRUITT,MOUNT DRUITT VILLAGE,MOUNT HUNTER,MOUNT HUTTON,MOUNT KEIRA,MOUNT LEWIS,MOUNT OUSLEY,MOUNT PLEASANT,MOUNT PRITCHARD,MOUNT RIVERVIEW,MOUNT SAINT THOMAS,MOUNT VICTORIA,MOUNT WARRIGAL,MOUNT WHITE,MOURQUONG,MUDGEE,MULGOA,MULLAWAY,MULLUMBIMBY,MURWILLUMBAH,MUSWELLBROOK,NABIAC,NAMBUCCA HEADS,NARARA,NARELLAN,NARELLAN VALE,NAREMBURN,NAROOMA,NARRABEEN,NARRANDERA,NARRAWALLEE,NARRAWEENA,NARROMINE,NARWEE,NASHUA,NELSON BAY,NEMINGHA,NERICON,NEUTRAL BAY,NEW BERRIMA,NEW LAMBTON,NEW LAMBTON HEIGHTS,NEWCASTLE,NEWCASTLE EAST,NEWCASTLE WEST,NEWINGTON,NEWPORT,NEWPORT BEACH,NEWRYBAR,NEWTOWN,NIAGARA PARK,NIMBIN,NIMMITABEL,NORAH HEAD,NORAVILLE,NORDS WHARF,NORFOLK ISLAND,NORMANHURST,NORTH ALBURY,NORTH ARM COVE,NORTH AVOCA,NORTH BONDI,NORTH CURL CURL,NORTH EPPING,NORTH GOSFORD,NORTH HAVEN,NORTH LAMBTON,NORTH MANLY,NORTH NARRABEEN,NORTH PARRAMATTA,NORTH RICHMOND,NORTH ROCKS,NORTH RYDE,NORTH ST MARYS,NORTH STRATHFIELD,NORTH SYDNEY,NORTH TAMWORTH,NORTH TURRAMURRA,NORTHBRIDGE,NORTHMEAD,NORTHWOOD,NOWRA,NOWRA NORTH,OAK FLATS,OAKHURST,OAKVILLE,OATLANDS,OATLEY,OBERON,OCEAN SHORES,OLD BAR,OLD JUNEE,OLD TOONGABBIE,ORANGE,ORANGE GROVE,ORCHARD HILLS,ORIENT POINT,OTFORD,OURIMBAH,OXLEY PARK,OXLEY VALE,OYSTER BAY,PADDINGTON,PADDYS RIVER,PADSTOW,PADSTOW HEIGHTS,PAGEWOOD,PALM BEACH,PALMERS ISLAND,PANANIA,PARKES,PARKLEA,PARRAMATTA,PATERSON,PAXTON,PEAK HILL,PEAKHURST,PEAKHURST HEIGHTS,PELAW MAIN,PELICAN,PEMULWUY,PENDLE HILL,PENNANT HILLS,PENRITH,PENSHURST,PERTHVILLE,PETERSHAM,PHEGANS BAY,PHILLIP BAY,PICNIC POINT,PICTON,PIGGABEEN,PILLAR VALLEY,PINDIMAR,PITT TOWN,PLUMPTON,POINT CLARE,POINT FREDERICK,POINT PIPER,PORT KEMBLA,PORT MACQUARIE,PORTLAND,POSSUM CREEK,POTTS POINT,POTTSVILLE,POTTSVILLE BEACH,PRAIRIEWOOD,PRESTONS,PRIMBEE,PROSPECT,PUNCHBOWL,PUTNEY,PYMBLE,PYRMONT,QUAKERS HILL,QUEANBEYAN,QUEENS PARK,QUEENSCLIFF,QUIRINDI,RABY,RAGLAN,RALEIGH,RAMSGATE,RAMSGATE BEACH,RANDWICK,RANDWICK NORTH,RANKIN PARK,RATHMINES,RAWORTH,RAYMOND TERRACE,REDFERN,REDHEAD,REGENTS PARK,REGENTVILLE,REVESBY,RHODES,RICHMOND,RIVERSTONE,RIVERVIEW,RIVERWOOD,ROBERTSON,ROCKDALE,ROCKLEY MOUNT,ROCKY POINT,RODD POINT,ROOKHURST,ROOTY HILL,ROPES CROSSING,ROSE BAY,ROSEBERY,ROSEHILL,ROSELANDS,ROSEMEADOW,ROSEVILLE,ROSEVILLE CHASE,ROSSMORE,ROTHBURY,ROUND CORNER,ROUSE HILL,ROZELLE,RUSE,RUSHCUTTERS BAY,RUSSELL LEA,RUSSELL VALE,RUTHERFORD,RYDALMERE,RYDE,RYE PARK,SADLEIR,SAFETY BEACH,SALAMANDER BAY,SAN REMO,SANCTUARY POINT,SANDRINGHAM,SANDY BEACH,SANS SOUCI,SAPPHIRE BEACH,SARATOGA,SAWTELL,SCHOFIELDS,SCONE,SCOTTS HEAD,SEAFORTH,SEAHAM,SEFTON,SEVEN HILLS,SHALVEY,SHELL COVE,SHELLHARBOUR,SHOAL BAY,SHOALHAVEN HEADS,SHORTLAND,SILVERDALE,SILVERWATER,SINGLETON,SINGLETON HEIGHTS,SKENNARS HEAD,SMITHFIELD,SMITHS LAKE,SMITHTOWN,SOLDIERS POINT,SOMERSBY,SOUTH ALBURY,SOUTH COOGEE,SOUTH DURRAS,SOUTH GOLDEN BEACH,SOUTH GRAFTON,SOUTH HURSTVILLE,SOUTH KEMPSEY,SOUTH LISMORE,SOUTH MAROOTA,SOUTH PENRITH,SOUTH TURRAMURRA,SOUTH WENTWORTHVILLE,SOUTH WEST ROCKS,SOUTH WINDSOR,SPEERS POINT,SPENCER,SPRING HILL,SPRINGFIELD,SPRINGWOOD,ST ANDREWS,ST CLAIR,ST GEORGES BASIN,ST HELENS PARK,ST IVES,ST JOHNS PARK,ST LEONARDS,ST MARYS,ST MARYS SOUTH,ST PETERS,STANHOPE,STANHOPE GARDENS,STANMORE,STANWELL PARK,STOCKTON,STRATFORD,STRATHFIELD,STRATHFIELD SOUTH,STROUD,SUFFOLK PARK,SUMMER HILL,SUMMERLAND POINT,SUNSHINE,SUNSHINE BAY,SURF BEACH,SURFSIDE,SURRY HILLS,SUSSEX INLET,SUTHERLAND,SUTTON FOREST,SWANSEA,SWANSEA HEADS,SYDENHAM,SYDNEY,SYLVANIA,SYLVANIA WATERS,TACOMA,TAHMOOR,TALLONG,TAMARAMA,TAMWORTH,TAMWORTH SOUTH,TANGLEWOOD,TANILBA BAY,TARBUCK BAY,TARCUTTA,TAREE,TAREN POINT,TARRAWANNA,TASCOTT,TATTON,TAYLORS BEACH,TEA GARDENS,TELARAH,TELOPEA,TEMORA,TEMPE,TENAMBIT,TENNYSON,TENNYSON POINT,TERALBA,TERRANORA,TERREY HILLS,TERRIGAL,TEVEN,THE CHANNON,THE ENTRANCE,THE ENTRANCE NORTH,THE HILL,THE JUNCTION,THE OAKS,THE ROCK,THE ROCKS,THIRLMERE,THIRROUL,THORNLEIGH,THORNTON,THREDBO VILLAGE,THURGOONA,TIGHES HILL,TINGIRA HEIGHTS,TINONEE,TOCUMWAL,TOLLAND,TOMAKIN,TOMERONG,TOONGABBIE,TOORMINA,TOOWOON BAY,TORONTO,TOUKLEY,TOWRADGI,TREGEAR,TRUNDLE,TUCABIA,TUCKOMBIL,TUGGERAH,TUGGERAWONG,TULLERA,TUMBI UMBI,TUMUT,TUNCURRY,TURA BEACH,TUROSS HEAD,TURRAMURRA,TURRELLA,TURVEY PARK,TWEED HEADS,TWEED HEADS SOUTH,TWEED HEADS WEST,TYALGUM,UKI,ULLADULLA,ULTIMO,UMINA BEACH,UNANDERRA,UPPER ORARA,URALLA,URANQUINTY,URLIUP,URUNGA,VALENTINE,VALLA BEACH,VAUCLUSE,VILLAWOOD,VINCENTIA,VINEYARD,VOYAGER POINT,WADALBA,WAGGA WAGGA,WAGSTAFFE,WAHROONGA,WAITARA,WAITUI,WAKELEY,WALLABI POINT,WALLACIA,WALLERAWANG,WALLSEND,WALSH BAY,WAMBERAL,WANGI WANGI,WARABROOK,WARATAH,WARATAH WEST,WARDELL,WARILLA,WARKWORTH,WARNERS BAY,WARNERVALE,WARRAGAMBA,WARRAWEE,WARRAWONG,WARRIEWOOD,WARRIMOO,WARWICK FARM,WATANOBBI,WATERLOO,WATSONS BAY,WATTLE GROVE,WAUCHOPE,WAVERLEY,WAVERTON,WEDDERBURN,WELLINGTON,WENTWORTH,WENTWORTH FALLS,WENTWORTHVILLE,WEROMBI,WERRINGTON,WERRINGTON COUNTY,WERRIS CREEK,WEST ALBURY,WEST BALLINA,WEST HOXTON,WEST KEMPSEY,WEST NOWRA,WEST PENNANT HILLS,WEST PYMBLE,WEST RYDE,WEST TAMWORTH,WEST WALLSEND,WEST WYALONG,WESTLEIGH,WESTMEAD,WETHERILL PARK,WHALAN,WHALE BEACH,WHEELER HEIGHTS,WHITEBRIDGE,WIANGAREE,WICKHAM,WILBERFORCE,WILEY PARK,WILLIAMTOWN,WILLMOT,WILLOUGHBY,WILSONS CREEK,WILTON,WINDALE,WINDANG,WINDERMERE PARK,WINDSOR,WINGELLO,WINGHAM,WINMALEE,WINSTON HILLS,WISEMANS FERRY,WOLLI CREEK,WOLLOMBI,WOLLONGBAR,WOLLONGONG,WOLLONGONG NORTH,WOLLONGONG WEST,WOLLSTONECRAFT,WONGARBON,WOODBERRY,WOODBINE,WOODCROFT,WOODFORD,WOODPARK,WOOLGOOLGA,WOOLI,WOOLLAHRA,WOOLLAMIA,WOOLLOOMOOLOO,WOOLOOWARE,WOOLWICH,WOONGARRAH,WOONONA,WORRIGEE,WOY WOY,WOY WOY BAY,WYALONG,WYEE,WYEE POINT,WYNDHAM,WYOMING,WYONG,WYONGAH,YAGOONA,YAMBA,YARRAS,YARRAVEL,YASS,YENDA,YERRINBOOL,YETHOLME,YOOGALI,YORKLEA,YOUNG,YOWIE BAY,ZETLAND"];
	[self fillDatabaseByIncludingAustralianList:TRUE forState:@"NT" andSuburbs:@"SHOW ALL,ALAWA,ALICE SPRINGS,ANULA,BAKEWELL,BAYVIEW,BERRY SPRINGS,BRINKIN,COCONUT GROVE,CULLEN BAY,DARWIN,DRIVER,DURACK,FANNIE BAY,FARRAR,GRAY,GUNN,HUMPTY DOO,JINGILI,KARAMA,LARRAKEYAH,LEANYER,LUDMILLA,MALAK,MARLOW LAGOON,MILLNER,MOIL,MOULDEN,NAKARA,NIGHTCLIFF,NORTHLAKES,PARAP,RAPID CREEK,ROSEBERY,ROSEBERY HEIGHTS,SOUTHPORT,STUART PARK,THE GARDENS,THE NARROWS,TIWI,WAGAMAN,WANGURI,WOODLEIGH GARDENS,WOODROFFE,WOOLNER,WULAGI"];
	[self fillDatabaseByIncludingAustralianList:TRUE forState:@"QLD" andSuburbs:@"SHOW ALL,ACACIA RIDGE,ACLAND,AGNES WATER,AIRLIE BEACH,AITKENVALE,ALBANY CREEK,ALBERTON,ALBION,ALDERLEY,ALEXANDRA HEADLAND,ALEXANDRA HILLS,ALGESTER,ALLENSTOWN,ALLENVIEW,ALLIGATOR CREEK,ALLORA,ALPHA,ANDERGROVE,ANNANDALE,ANNERLEY,ANSTEAD,APPLE TREE CREEK,APPLETHORPE,ARANA HILLS,ARATULA,ARCHERFIELD,ARMSTRONG BEACH,AROONA,ARUNDEL,ASCOT,ASHGROVE,ASHMORE,ASPLEY,ATHERTON,AUCHENFLOWER,AVENELL HEIGHTS,AVOCA,AYR,BAHRS SCRUB,BAKERS CREEK,BALD HILLS,BALGAL BEACH,BALL BAY,BALLANDEAN,BALMORAL,BANANA,BANGALEE,BANKSIA BEACH,BANYO,BARALABA,BARDON,BARELLAN POINT,BARGARA,BARNEY POINT,BASIN POCKET,BATTERY HILL,BAUPLE,BAYVIEW HEIGHTS,BEACHMERE,BEACONSFIELD,BEAUDESERT,BEECHER,BEECHMONT,BEENLEIGH,BEERBURRUM,BEERWAH,BELGIAN GARDENS,BELIVAH,BELLARA,BELLBIRD PARK,BELLBOWRIE,BELLMERE,BELMONT,BENARABY,BENOWA,BENTLEY PARK,BERSERKER,BETHANIA,BIDDESTON,BIGGENDEN,BIGGERA WATERS,BILINGA,BILOELA,BIRKDALE,BIRTINYA,BLACK MOUNTAIN,BLACKBUTT,BLACKS BEACH,BLACKSTONE,BLACKWATER,BLI BLI,BLOOMSBURY,BLUEWATER,BLUFF,BOHLE PLAINS,BONGAREE,BOONAH,BOONDALL,BOOVAL,BOREEN POINT,BORONIA HEIGHTS,BOWEN,BOWEN HILLS,BOYLAND,BOYNE ISLAND,BRACKEN RIDGE,BRAMSTON BEACH,BRASSALL,BRAY PARK,BRENDALE,BRIBIE ISLAND,BRIDGEMAN DOWNS,BRIGHTON,BRINSMEAD,BRISBANE,BROADBEACH,BROADBEACH WATERS,BROOKFIELD,BROOKWATER,BROWNS PLAINS,BUCASIA,BUCCAN,BUDDINA,BUDERIM,BULIMBA,BUNDABERG,BUNDABERG CENTRAL,BUNDABERG NORTH,BUNDABERG SOUTH,BUNDABERG WEST,BUNDALL,BUNDAMBA,BUNGALOW,BURANDA,BURDELL,BURLEIGH HEADS,BURLEIGH WATERS,BURNETT HEADS,BURNSIDE,BURPENGARY,BURRUM HEADS,BURRUM TOWN,BUSHLAND BEACH,BUXTON,CABBAGE TREE POINT,CABOOLTURE,CABOOLTURE SOUTH,CAIRNS,CAIRNS CITY,CAIRNS NORTH,CALAMVALE,CALAVOS,CALLIOPE,CALOUNDRA,CALOUNDRA WEST,CALVERT,CAMBOOYA,CAMIRA,CAMP HILL,CAMPWIN BEACH,CANNON HILL,CANNONVALE,CANUNGRA,CAPALABA,CAPTAIN CREEK,CARAVONICA,CARDWELL,CARINA,CARINA HEIGHTS,CARINDALE,CAROLE PARK,CARRARA,CARSELDINE,CASHMERE,CASTAWAYS BEACH,CASTLE HILL,CAWARRAL,CECIL PLAINS,CEDAR GROVE,CEDAR VALE,CENTENARY HEIGHTS,CHAMBERS FLAT,CHAPEL HILL,CHARTERS TOWERS,CHELMER,CHERMSIDE,CHERMSIDE WEST,CHEVRON ISLAND,CHILDERS,CHINCHILLA,CHIRN PARK,CHURCHILL,CLAYFIELD,CLEAR ISLAND WATERS,CLERMONT,CLEVELAND,CLIFFORD GARDENS,CLIFTON,CLIFTON BEACH,CLINTON,CLONTARF,CLOSEBURN,COALFALLS,COES CREEK,COLINTON,COLLEGE VIEW,COLLINGWOOD PARK,COLLINSVILLE,COLSTON PARK,CONDON,CONINGSBY,CONWAY,COOCHIEMUDLO ISLAND,COOLABINE,COOLANGATTA,COOLOOLA,COOLOOLA COVE,COOLUM BEACH,COOMBABAH,COOMERA,COOMINYA,COOPERS PLAINS,COORAN,COOROY,COORPAROO,CORAL COVE,CORINDA,CORNUBIA,COTTON TREE,CRAIGNISH,CRANBROOK,CRESTMEAD,CROWS NEST,CURRA,CURRAJONG,CURRIMUNDI,CURRUMBIN,CURRUMBIN VALLEY,CURRUMBIN WATERS,DAISY HILL,DAKABIN,DALBY,DARLING HEIGHTS,DARRA,DAYBORO,DEAGON,DECEPTION BAY,DEEBING HEIGHTS,DEERAGUN,DICKY BEACH,DIDDILLIBAH,DINGO BEACH,DINMORE,DOLPHIN HEADS,DOOLANDELLA,DOOLBI,DOONAN,DOUGLAS,DRAYTON,DREWVALE,DUNDOWRAN,DUNDOWRAN BEACH,DURACK,DUTTON PARK,DYSART,EAGLE HEIGHTS,EAGLEBY,EARLVILLE,EAST BRISBANE,EAST IPSWICH,EAST MACKAY,EAST TOOWOOMBA,EAST TRINITY,EASTERN HEIGHTS,EATONS HILL,EDENS LANDING,EDGE HILL,EDMONTON,EIGHT MILE PLAINS,EIMEO,ELANORA,ELI WATERS,ELIMBAH,ELLIOTT HEADS,EMERALD,EMU PARK,ENOGGERA,EPHRAIM ISLAND,ESK,EUMUNDI,EVERTON HILLS,EVERTON PARK,FAIRFIELD,FELUGA,FERNVALE,FERNY GROVE,FERNY HILLS,FIG TREE POCKET,FINCH HATTON,FITZGIBBON,FLAXTON,FLINDERS VIEW,FLYING FISH POINT,FOREST CREEK,FOREST HILL,FOREST LAKE,FORMARTIN,FORREST BEACH,FORTITUDE VALLEY,FRENCHVILLE,FRESHWATER,GARBUTT,GATTON,GAVEN,GAYTHORNE,GEEBUNG,GHOST HILL,GILSTON,GIN GIN,GLADSTONE,GLADSTONE SOUTH,GLASS HOUSE MOUNTAINS,GLASTONBURY,GLENDEN,GLENEAGLE,GLENELLA,GLENORE GROVE,GLENVALE,GLENWOOD,GOLDEN BEACH,GOODNA,GOOMBUNGEE,GOOMERI,GOONDIWINDI,GORDON PARK,GORDONVALE,GOWRIE JUNCTION,GRACEMERE,GRACEVILLE,GRANGE,GRANVILLE,GRASSTREE BEACH,GREENBANK,GREENMOUNT,GREENSLOPES,GREGORS CREEK,GUANABA,GULLIVER,GYMPIE,HABANA,HALIDAY BAY,HALIFAX,HAMILTON,HAMILTON ISLAND,HAMPTON,HARLAXTON,HARRISTOWN,HATTON VALE,HAWTHORNE,HEATHWOOD,HEATLEY,HELENSVALE,HELIDON,HEMMANT,HENDRA,HERITAGE PARK,HERMIT PARK,HERSTON,HERVEY BAY,HIDEAWAY BAY,HIGHFIELDS,HIGHGATE HILL,HIGHLAND PARK,HILLCREST,HODGSON VALE,HOLLAND PARK,HOLLAND PARK WEST,HOLLOWAYS BEACH,HOLLYWELL,HOLMVIEW,HOPE ISLAND,HORTON,HOWARD,HYDE PARK,IDALIA,IMBIL,INALA,INDOOROOPILLY,INGHAM,INNES PARK,INNISFAIL,IPSWICH,ISLE OF CAPRI,JACOBS WELL,JAMBOREE HEIGHTS,JANDOWAE,JENSEN,JIMBOOMBA,JINDALEE,JOYNER,JUBILEE POCKET,KALBAR,KALLANGUR,KAMERUNGA,KANGAROO POINT,KANIMBLA,KARANA DOWNS,KARRAGARRA ISLAND,KAWANA,KAWANA ISLAND,KAWUNGAN,KEARNEYS SPRING,KEDRON,KELSO,KELVIN GROVE,KENILWORTH,KENMORE,KENMORE HILLS,KEPERRA,KEPNOCK,KEPPEL SANDS,KERRY,KEWARRA BEACH,KHOLO,KILCOY,KILKIVAN,KIN KIN,KINGAROY,KINGS BEACH,KINGSTHORPE,KINGSTON,KIPPA-RING,KIRRA,KIRWAN,KOORALBYN,KULPI,KUMBIA,KURABY,KURANDA,KURRIMINE BEACH,KURWONGBAH,LABRADOR,LAGUNA QUAYS,LAIDLEY,LAMB ISLAND,LANDSBOROUGH,LANGSHAW,LAWNTON,LEICHHARDT,LEYBURN,LITTLE MOUNTAIN,LOCKYER WATERS,LOGAN CENTRAL,LOGAN RESERVE,LOGANHOLME,LOGANLEA,LONGREACH,LOTA,LOWER BEECHMONT,LOWER TENTHILL,LOWOOD,LUCINDA,LUTWYCHE,LYONS,MACGREGOR,MACKAY,MACKAY HARBOUR,MACKAY NORTH,MACKAY SOUTH,MACKENZIE,MACLEAY ISLAND,MAGNETIC ISLAND,MAIDENWELL,MAIN BEACH,MALENY,MANGO HILL,MANLY,MANLY WEST,MANOORA,MANSFIELD,MANUNDA,MAPLETON,MARCOOLA,MAREEBA,MARGATE,MARGATE BEACH,MARIAN,MAROOCHY RIVER,MAROOCHYDORE,MAROON,MARSDEN,MARYBOROUGH,MARYBOROUGH WEST,MARYVALE,MAUDSLAND,MCDOWALL,MEADOWBROOK,MERIDAN PLAINS,MERINGANDAN,MERMAID BEACH,MERMAID WATERS,MERRIMAC,MIAMI,MIDDLE PARK,MIDDLE RIDGE,MIDDLEMOUNT,MIDGE POINT,MILES,MILLBANK,MILMAN,MILTON,MINYAMA,MISSION BEACH,MITCHELTON,MOFFAT BEACH,MOFFATDALE,MOGGILL,MOLENDINAR,MONKLAND,MONTEREY KEYS,MONTVILLE,MOOLOOLABA,MOOLOOLAH,MOORE PARK,MOORE PARK BEACH,MOOROOBOOL,MOOROOKA,MORANBAH,MORAYFIELD,MORNINGSIDE,MOSSMAN,MOUNT COOLUM,MOUNT COTTON,MOUNT FORBES,MOUNT GRAVATT,MOUNT GRAVATT EAST,MOUNT ISA,MOUNT KYNOCH,MOUNT LOFTY,MOUNT LOUISA,MOUNT MARSHALL,MOUNT NATHAN,MOUNT OMMANEY,MOUNT PLEASANT,MOUNT SHERIDAN,MOUNT TARAMPA,MOUNT WARREN PARK,MOUNTAIN CREEK,MOURA,MUDGEERABA,MUDJIMBA,MULAMBIN,MUNDINGBURRA,MURARRIE,MURGON,MURPHYS CREEK,MURRUMBA DOWNS,MYSTERTON,NAMBOUR,NANANGO,NARANGBA,NATHAN,NEBO,NELLY BAY,NERANG,NERIMBERA,NEW AUCKLAND,NEW BEITH,NEW FARM,NEWELL,NEWMARKET,NEWSTEAD,NEWTOWN,NINGI,NOOSA HEADS,NOOSA WATERS,NOOSAVILLE,NORMAN GARDENS,NORMAN PARK,NORTH ARM,NORTH BOOVAL,NORTH IPSWICH,NORTH LAKES,NORTH MACKAY,NORTH ROCKHAMPTON,NORTH TAMBORINE,NORTH TOOWOOMBA,NORTH WARD,NORTHGATE,NORVILLE,NORWELL,NUDGEE,NUNDAH,OAK VALLEY,OAKEY,OAKHURST,ONE MILE,OONOONBA,ORMEAU,ORMISTON,OXENFORD,OXLEY,PACIFIC HEIGHTS,PACIFIC PARADISE,PACIFIC PINES,PADDINGTON,PALLARENDA,PALM BEACH,PALM COVE,PALMVIEW,PALMWOODS,PARADISE ISLAND,PARADISE POINT,PARADISE WATERS,PARK AVENUE,PARK RIDGE,PARK RIDGE SOUTH,PARKHURST,PARKINSON,PARKWOOD,PARRAMATTA PARK,PARREARRA,PATERSON,PEACHESTER,PELICAN WATERS,PEREGIAN BEACH,PEREGIAN SPRINGS,PETRIE,PETRIE TERRACE,PIALBA,PILTON,PIMLICO,PIMPAMA,PINBARREN,PITTSWORTH,PLACID HILLS,PLAINLAND,PLANLAND,PLEYSTOWE,POINT VERNON,POMONA,PORT DOUGLAS,PROSERPINE,PULLENVALE,QUNABA,RABY BAY,RACEVIEW,RAILWAY ESTATE,RAINBOW BAY,RAINBOW BEACH,RANGEVILLE,RASMUSSEN,RATHDOWNEY,RAVENSBOURNE,RED HILL,REDBANK,REDBANK PLAINS,REDCLIFFE,REDLAND BAY,REDLYNCH,REEDY CREEK,REGENCY DOWNS,REGENTS PARK,RICHLANDS,RIPLEY,RIVER HEADS,RIVERHILLS,RIVERVIEW,ROBERTSON,ROBINA,ROCHEDALE,ROCHEDALE SOUTH,ROCKHAMPTON,ROCKHAMPTON CITY,ROCKLEA,ROCKSBERG,ROCKVILLE,ROMA,ROSALIE,ROSEMOUNT,ROSEWOOD,ROSSLEA,ROTHWELL,ROWES BAY,RUNAWAY BAY,RUNCORN,RUNNYMEDE,RURAL VIEW,RUSSELL ISLAND,SADLIERS CROSSING,SALISBURY,SALONIKA BEACH,SAMFORD,SAMFORD VALLEY,SAMFORD VILLAGE,SANCTUARY COVE,SANDGATE,SANDSTONE POINT,SANTA BARBARA,SARINA,SARINA BEACH,SAUNDERS BEACH,SCARBOROUGH,SCARNESS,SCOTTVILLE,SCRUBBY CREEK,SEAFORTH,SEVEN HILLS,SEVENTEEN MILE ROCKS,SEVENTEEN SEVENTY,SHAILER PARK,SHELDON,SHELLY BEACH,SHERWOOD,SHOAL POINT,SHORNCLIFFE,SHUTE HARBOUR,SILKSTONE,SINNAMON PARK,SIPPY DOWNS,SLACKS CREEK,SLADE POINT,SMITHFIELD,SOMERSET DAM,SORRENTO,SOUTH BANK,SOUTH BRISBANE,SOUTH GLADSTONE,SOUTH MACKAY,SOUTH MACLEAN,SOUTH TOOWOOMBA,SOUTH TOWNSVILLE,SOUTHBROOK,SOUTHPORT,SOUTHSIDE,SOVEREIGN ISLANDS,SPRING HILL,SPRINGBROOK,SPRINGFIELD,SPRINGFIELD LAKES,SPRINGWOOD,ST LUCIA,STAFFORD,STAFFORD HEIGHTS,STANTHORPE,STONES CORNER,STRATFORD,STRATHDICKIE,STRATHPINE,STRETTON,SUMNER,SUNNYBANK,SUNNYBANK HILLS,SUNRISE BEACH,SUNSHINE BEACH,SURAT,SURFERS PARADISE,SVENSSON HEIGHTS,TAIGUM,TALLAI,TALLEBUDGERA,TALLEBUDGERA VALLEY,TAMBORINE,TAMROOKUM,TANAH MERAH,TANAWHA,TANNUM SANDS,TARINGA,TARRAGINDI,TAYLORS BEACH,TENERIFFE,TENNYSON,TEWANTIN,THABEBAN,THAGOONA,THE GAP,THE LEAP,THE RANGE,THEODORE,THORNESIDE,THORNLANDS,TIARO,TIN CAN BAY,TINANA,TINGALPA,TINGOORA,TIRROAN,TIVOLI,TOLGA,TOOGOOLAWAH,TOOGOOM,TOOLAKEA,TOOMBUL,TOORBUL,TOOWONG,TOOWOOMBA,TOOWOOMBA CITY,TORBANLEA,TORQUAY,TORRINGTON,TOWNSVILLE,TOWNSVILLE CITY,TOWNSVILLE WEST,TRAVESTON,TRINITY BEACH,TRINITY PARK,TUAN,TUGUN,TULLY,TULLY HEADS,TWIN WATERS,UNDERWOOD,UPPER CABOOLTURE,UPPER COOMERA,UPPER KEDRON,UPPER MOUNT GRAVATT,URANGAN,URRAWEEN,VARSITY LAKES,VICTORIA POINT,VIRGINIA,WACOL,WAKERLEY,WALKERSTON,WALLANGARRA,WALLOON,WAMURAN,WANDAL,WARANA,WARNER,WARRA,WARWICK,WATERFORD,WATERFORD WEST,WAVELL HEIGHTS,WEIPA,WELLINGTON POINT,WEST BURLEIGH,WEST END,WEST GLADSTONE,WEST MACKAY,WESTBROOK,WESTCOURT,WESTLAKE,WHITE ROCK,WHITFIELD,WHITSUNDAYS,WILLOWBANK,WILSONS POCKET,WILSONTON,WILSTON,WINDSOR,WISHART,WITHCOTT,WONDAI,WONDUNNA,WONGA,WONGAWALLAN,WOODEND,WOODGATE,WOODLANDS,WOODRIDGE,WOODY POINT,WOOLLOONGABBA,WOOLOOWIN,WOOMBYE,WOORIM,WOOROOLIN,WOREE,WORONGARY,WULGURU,WULKURAKA,WURDONG HEIGHTS,WURTULLA,WYNNUM,WYNNUM WEST,WYREEMA,YAMANTO,YANDINA,YARRAMAN,YEERONGPILLY,YEPPOON,YERONGA,YORKEYS KNOB,ZILLMERE,ZILZIE"];
	[self fillDatabaseByIncludingAustralianList:TRUE forState:@"SA" andSuburbs:@"SHOW ALL,ABERFOYLE PARK,ADELAIDE,ALBERT PARK,ALBERTON,ALDGATE,ALDINGA,ALDINGA BEACH,ALLENBY GARDENS,AMERICAN RIVER,ANDAMOOKA,ANDREWS FARM,ANGASTON,ANGLE PARK,ASCOT PARK,ASHFORD,ATHELSTONE,ATHOL PARK,AUBURN,BALHANNAH,BANKSIA PARK,BARMERA,BEAUMONT,BEDFORD PARK,BELAIR,BELLEVUE HEIGHTS,BERRI,BEULAH PARK,BIRDWOOD,BIRKENHEAD,BLACK FOREST,BLACKWOOD,BLAIR ATHOL,BLAKEVIEW,BLYTH,BORDERTOWN,BRAHMA LODGE,BRIDGEWATER,BRIGHTON,BROADVIEW,BROMPTON,BROOKLYN PARK,BROWNLOW,BUGLE RANGES,BURNSIDE,BURRA,BURTON,CALLINGTON,CAMDEN PARK,CAMPBELLTOWN,CARRICKALINGA,CHELTENHAM,CHRISTIES BEACH,CLAPHAM,CLARE,CLARENCE GARDENS,CLARENCE PARK,CLARENDON,CLAYTON,CLEARVIEW,CLEVE,CLOVELLY PARK,COLLEGE PARK,COLLINSWOOD,COLONEL LIGHT GARDENS,COOBER PEDY,COOLTONG,COROMANDEL VALLEY,COWANDILLA,CRAFERS,CRAIGMORE,CROYDON,CROYDON PARK,CRYSTAL BROOK,CUMBERLAND PARK,CUMMINS,DARLINGTON,DAVOREN PARK,DAW PARK,DERNANCOURT,DEVON PARK,DOVER GARDENS,DULWICH,EASTWOOD,ECHUNGA,EDEN HILLS,EDWARDSTOWN,EIGHT MILE CREEK,ELIZABETH,ELIZABETH DOWNS,ELIZABETH EAST,ELIZABETH GROVE,ELIZABETH NORTH,ELIZABETH PARK,ELIZABETH SOUTH,ELIZABETH VALE,ENCOUNTER BAY,ENFIELD,ERINDALE,ETHELTON,EUDUNDA,EVANDALE,EVANSTON,EVANSTON PARK,EVANSTON SOUTH,EVERARD PARK,EXETER,FAIRVIEW PARK,FARRELL FLAT,FELIXSTOW,FERRYDEN PARK,FINDON,FIRLE,FITZROY,FLAGSTAFF HILL,FLINDERS PARK,FORESTVILLE,FREELING,FULHAM,FULHAM GARDENS,FULLARTON,GAWLER,GAWLER EAST,GAWLER SOUTH,GAWLER WEST,GEPPS CROSS,GILBERTON,GILLES PLAINS,GLADSTONE,GLANDORE,GLANVILLE,GLEN OSMOND,GLENALTA,GLENELG,GLENELG EAST,GLENELG NORTH,GLENELG SOUTH,GLENGOWRIE,GLENSIDE,GLENUNGA,GLOSSOP,GLYNDE,GOLDEN GROVE,GOODWOOD,GOOLWA,GOOLWA BEACH,GOOLWA NORTH,GOOLWA SOUTH,GRANGE,GREENACRES,GREENWITH,GULFVIEW HEIGHTS,GULNARE,HACKHAM,HACKHAM WEST,HACKNEY,HAHNDORF,HALLETT COVE,HAMPSTEAD GARDENS,HANSON,HAPPY VALLEY,HARDWICKE BAY,HARTLEY,HAWTHORN,HAYBOROUGH,HAZELWOOD PARK,HEATHFIELD,HEATHPOOL,HECTORVILLE,HENDON,HENLEY BEACH,HENLEY BEACH SOUTH,HEWETT,HIGHBURY,HIGHGATE,HILLBANK,HILLCREST,HINDMARSH ISLAND,HOLDEN HILL,HOPE VALLEY,HOVE,HUNTFIELD HEIGHTS,HYDE PARK,INGLE FARM,INMAN VALLEY,JAMESTOWN,JOSLIN,KADINA,KALANGADOO,KAPUNDA,KENSINGTON,KENSINGTON GARDENS,KENSINGTON PARK,KENT TOWN,KESWICK,KIDMAN PARK,KILBURN,KILKENNY,KINGS PARK,KINGSTON ON MURRAY,KINGSTON PARK,KINGSTON SE,KINGSWOOD,KLEMZIG,KURRALTA PARK,LARGS BAY,LARGS NORTH,LEABROOK,LEAWOOD GARDENS,LENSWOOD,LEWISTON,LINDEN PARK,LITTLEHAMPTON,LOBETHAL,LOCKLEYS,LONGWOOD,LOUTH BAY,LOWER MITCHAM,LOXTON,LOXTON NORTH,LUCINDALE,MACCLESFIELD,MAGILL,MALVERN,MANNINGHAM,MANNUM,MANSFIELD PARK,MARDEN,MARINO,MARION,MARLESTON,MARRYATVILLE,MASLIN BEACH,MAWSON LAKES,MAYLANDS,MCLAREN FLAT,MCLAREN VALE,MEDINDIE,MELROSE PARK,MIDDLETON,MILANG,MILE END,MILLSWOOD,MINLATON,MITCHAM,MITCHELL PARK,MOANA,MODBURY,MODBURY HEIGHTS,MODBURY NORTH,MONASH,MOONTA BAY,MOORAK,MOOROOK,MORPHETT VALE,MORPHETTVILLE,MOUNT BARKER,MOUNT COMPASS,MOUNT GAMBIER,MOUNT OSMOND,MOUNT TORRENS,MUNNO PARA,MUNNO PARA WEST,MURRAY BRIDGE,MYLOR,MYRTLE BANK,NAILSWORTH,NAIRNE,NANGWARRY,NAPPERBY,NARACOORTE,NETHERBY,NETLEY,NEWTON,NILDOTTIE,NOARLUNGA DOWNS,NORMANVILLE,NORTH ADELAIDE,NORTH BRIGHTON,NORTH HAVEN,NORTH PLYMPTON,NORTHFIELD,NORTHGATE,NORTON SUMMIT,NORWOOD,NOVAR GARDENS,NURIOOTPA,O'HALLORAN HILL,O'SULLIVAN BEACH,OAKDEN,OAKLANDS PARK,OLD NOARLUNGA,OLD REYNELLA,ONE TREE HILL,OSBORNE,OTTOWAY,OVINGHAM,PADTHAWAY,PANORAMA,PARA HILLS,PARA HILLS WEST,PARA VISTA,PARACOMBE,PARADISE,PARAFIELD GARDENS,PARALOWIE,PARINGA,PARK HOLME,PARKSIDE,PARRAKIE,PASADENA,PAYNEHAM,PAYNEHAM SOUTH,PENNESHAW,PENNINGTON,PENOLA,PETERBOROUGH,PETERHEAD,PLYMPTON,POORAKA,PORT ADELAIDE,PORT AUGUSTA,PORT AUGUSTA WEST,PORT BROUGHTON,PORT ELLIOT,PORT GERMEIN,PORT LINCOLN,PORT MACDONNELL,PORT NOARLUNGA,PORT NOARLUNGA SOUTH,PORT PIRIE,PORT PIRIE WEST,PORT WILLUNGA,PROSPECT,PUNTHARI,QUEENSTOWN,QUORN,REDWOOD PARK,RENMARK,RENOWN PARK,REYNELLA,RICHMOND,RIDGEHAVEN,RIDLEYTON,RIVERTON,ROBE,ROSE PARK,ROSEWATER,ROSEWORTHY,ROSSLYN PARK,ROSTREVOR,ROXBY DOWNS,ROYAL PARK,ROYSTON PARK,SADDLEWORTH,SALISBURY,SALISBURY DOWNS,SALISBURY EAST,SALISBURY HEIGHTS,SALISBURY NORTH,SEACLIFF,SEACLIFF PARK,SEACOMBE GARDENS,SEACOMBE HEIGHTS,SEAFORD,SEAFORD RISE,SEATON,SEAVIEW DOWNS,SECOND VALLEY,SEFTON PARK,SELLICKS BEACH,SEMAPHORE,SEMAPHORE PARK,SEMAPHORE SOUTH,SHEIDOW PARK,SKYE,SMITHFIELD,SMITHFIELD PLAINS,SNOWTOWN,SOLOMONTOWN,SOMERTON PARK,SOUTH BRIGHTON,SOUTH PLYMPTON,SOUTHEND,SPALDING,ST AGNES,ST GEORGES,ST MARYS,ST MORRIS,ST PETERS,STEPNEY,STIRLING,STIRLING NORTH,STONYFELL,STRATHALBYN,STURT,SURREY DOWNS,TAILEM BEND,TANUNDA,TAPEROO,TARPEENA,TEA TREE GULLY,TENNYSON,THE PINES,THEBARTON,THORNGATE,TOORAK GARDENS,TORRENS PARK,TORRENSVILLE,TRANMERE,TRINITY GARDENS,TROTT PARK,TUMBY BAY,TUSMORE,TWO WELLS,UNDERDALE,UNLEY,UNLEY PARK,UPPER STURT,URRBRAE,VALE PARK,VALLEY VIEW,VICTOR HARBOR,VIRGINIA,WAIKERIE,WALKERVILLE,WALKLEY HEIGHTS,WALLAROO,WARD BELT,WARNERTOWN,WARRADALE,WASLEYS,WATERLOO CORNER,WATTLE PARK,WAYVILLE,WELLAND,WEST BEACH,WEST CROYDON,WEST LAKES,WEST LAKES SHORE,WEST RICHMOND,WESTBOURNE PARK,WHITE SANDS,WHYALLA,WHYALLA NORRIE,WHYALLA PLAYFORD,WHYALLA STUART,WILLASTON,WILLIAMSTOWN,WILLUNGA,WINDSOR,WINDSOR GARDENS,WINKIE,WIRRABARA,WIRRINA COVE,WOODCROFT,WOODS POINT,WOODSIDE,WOODVILLE,WOODVILLE GARDENS,WOODVILLE NORTH,WOODVILLE PARK,WOODVILLE SOUTH,WOODVILLE WEST,WYNN VALE,YAHL,YANKALILLA,YORKETOWN,YOUNGHUSBAND"];
	[self fillDatabaseByIncludingAustralianList:TRUE forState:@"TAS" andSuburbs:@"SHOW ALL,AUSTINS FERRY,BATTERY POINT,BEACONSFIELD,BEAUTY POINT,BELLERIVE,BERRIEDALE,BICHENO,BLACKMANS BAY,BLACKSTONE HEIGHTS,BLACKWALL,BONNET HILL,BRANXHOLM,BRIDGEWATER,BRIDPORT,BRIGHTON,BURNIE,CAMPBELL TOWN,CARLTON,CHIGWELL,CLAREMONT,CLIFTON BEACH,COLES BAY,CONINGHAM,COOEE,COWRIE POINT,CYGNET,DELORAINE,DERBY,DERWENT PARK,DEVIOT,DEVONPORT,DODGES FERRY,DOLPHIN SANDS,DULCOT,DUNALLEY,DYNNYRNE,EAST DEVONPORT,EAST LAUNCESTON,ELLENDALE,ELPHIN,EXETER,FOREST,FRANKLIN,GAGEBROOK,GEILSTON BAY,GEORGE TOWN,GLEBE,GLENORCHY,GOODWOOD,GRAVELLY BEACH,GREENS BEACH,GUNNS PLAINS,HADSPEN,HAWLEY BEACH,HEYBRIDGE,HILLWOOD,HOBART,HOWRAH,HUNTINGFIELD,HUONVILLE,INVERMAY,KAYENA,KINGS MEADOWS,KINGSTON,KINGSTON BEACH,LAPOINYA,LATROBE,LAUDERDALE,LAUNCESTON,LEGANA,LEITH,LENAH VALLEY,LEWISHAM,LINDISFARNE,LONGFORD,LOW HEAD,LOWER BARRINGTON,LULWORTH,LUTANA,MARGATE,MAYDENA,MAYFIELD,MIDDLETON,MIDWAY POINT,MONTAGU BAY,MONTROSE,MOONAH,MORNINGTON,MOUNT NELSON,MOUNT STUART,MOWBRAY,NEW NORFOLK,NEW TOWN,NEWNHAM,NEWSTEAD,NORTH HOBART,NORWOOD,NUBEENA,NUNAMARA,OAKDOWNS,OCEAN VISTA,OLD BEACH,OPOSSUM BAY,ORFORD,OTAGO,PENGUIN,PENNA,PERTH,PORT ARTHUR,PORT SORELL,PRIMROSE SANDS,PROSPECT,PYENGANA,QUEENSTOWN,QUOIBA,RAILTON,RAVENSWOOD,RICHMOND,RISDON VALE,RIVERSIDE,ROCHERLEA,ROKEBY,ROSE BAY,ROSEBERY,ROSETTA,SANDY BAY,SCOTTSDALE,SEVEN MILE BEACH,SHEARWATER,SHEFFIELD,SISTERS BEACH,SMITHTON,SOMERSET,SORELL,SOUTH HOBART,SOUTH LAUNCESTON,SPRENT,SPREYTON,ST HELENS,ST MARYS,STANLEY,SULPHUR CREEK,SUMMERHILL,SWAN BAY,SWAN POINT,SWANSEA,TAROONA,TRANMERE,TREVALLYN,TRIABUNNA,TURNERS BEACH,ULVERSTONE,UPPER BURNIE,WARATAH,WARRANE,WAVERLEY,WESLEY VALE,WEST HOBART,WEST LAUNCESTON,WEST MOONAH,WESTBURY,WESTERWAY,WEYMOUTH,WINDERMERE,WINKLEIGH,WOODBRIDGE,WYNYARD,YOLLA,YOUNGTOWN,ZEEHAN"];
	[self fillDatabaseByIncludingAustralianList:TRUE forState:@"VIC" andSuburbs:@"SHOW ALL,ABBOTSFORD,ABERFELDIE,AIRPORT WEST,ALBERT PARK,ALBERTON,ALBION,ALEXANDRA,ALFREDTON,ALLANSFORD,ALPHINGTON,ALTONA,ALTONA MEADOWS,ALTONA NORTH,ANAKIE,ANGLESEA,ARARAT,ARDEER,ARMADALE,ARTHURS SEAT,ASCOT VALE,ASHBURTON,ASHWOOD,ASPENDALE,ASPENDALE GARDENS,AVENEL,AVONDALE HEIGHTS,AVONSLEIGH,AXEDALE,BACCHUS MARSH,BAIRNSDALE,BALACLAVA,BALLAN,BALLARAT,BALLARAT CENTRAL,BALLARAT EAST,BALLARAT NORTH,BALLENDELLA,BALNARRING,BALWYN,BALWYN NORTH,BANNOCKBURN,BARANDUDA,BARONGAROOK,BARWON HEADS,BASS,BAXTER,BAYSWATER,BAYSWATER NORTH,BEACONSFIELD,BEAUFORT,BEAUMARIS,BEEAC,BEECHWORTH,BELGRAVE,BELGRAVE SOUTH,BELL PARK,BELL POST HILL,BELLBRAE,BELLFIELD,BELMONT,BENALLA,BENDIGO,BENTLEIGH,BENTLEIGH EAST,BERWICK,BET BET,BEVERIDGE,BIRREGURRA,BITTERN,BLACK HILL,BLACK ROCK,BLACKBURN,BLACKBURN NORTH,BLACKBURN SOUTH,BLAIRGOWRIE,BLAMPIED,BLIND BIGHT,BOISDALE,BOLWARRA,BONBEACH,BONEGILLA,BONNIE DOON,BOOLARRA,BORONIA,BOX HILL,BOX HILL NORTH,BOX HILL SOUTH,BRAYBROOK,BREAKWATER,BRIAGOLONG,BRIAR HILL,BRIGHT,BRIGHTON,BRIGHTON EAST,BROADFORD,BROADMEADOWS,BROOKFIELD,BROOKLYN,BROWN HILL,BRUNSWICK,BRUNSWICK EAST,BRUNSWICK WEST,BULLARTO,BULLEEN,BUNDOORA,BUNINYONG,BUNYIP,BURNLEY,BURNSIDE,BURWOOD,BURWOOD EAST,BUXTON,CABARITA,CAIRNLEA,CALIFORNIA GULLY,CALLIGNEE,CAMBERWELL,CAMPBELLFIELD,CAMPBELLS CREEK,CAMPERDOWN,CANADIAN,CANNONS CREEK,CANTERBURY,CAPE PATERSON,CAPE SCHANCK,CAPE WOOLAMAI,CARDIGAN VILLAGE,CARDROSS,CARISBROOK,CARLTON,CARLTON NORTH,CARNEGIE,CAROLINE SPRINGS,CARRUM,CARRUM DOWNS,CARWARP,CASTLEMAINE,CAULFIELD,CAULFIELD EAST,CAULFIELD NORTH,CAULFIELD SOUTH,CERES,CHADSTONE,CHELSEA,CHELSEA HEIGHTS,CHELTENHAM,CHEWTON,CHILTERN,CHIRNSIDE PARK,CHURCHILL,CLARINDA,CLAYTON,CLAYTON NORTH,CLAYTON SOUTH,CLIFTON HILL,CLIFTON SPRINGS,CLUNES,COBDEN,COBRAM,COBURG,COBURG NORTH,COCKATOO,COLAC,COLAC WEST,COLBINABBIN,COLDSTREAM,COLLINGWOOD,CONGUPNA,COOLAROO,CORIO,CORONET BAY,COROROOKE,CORRYONG,COTTLES BRIDGE,COWES,CRAIGIEBURN,CRANBOURNE,CRANBOURNE EAST,CRANBOURNE NORTH,CRANBOURNE SOUTH,CRANBOURNE WEST,CREMORNE,CRESWICK,CRIB POINT,CROYDON,CROYDON HILLS,CROYDON NORTH,CROYDON SOUTH,CUDGEWA,DALLAS,DALYSTON,DANDENONG,DANDENONG NORTH,DANDENONG SOUTH,DARLEY,DAYLESFORD,DEAN,DEER PARK,DELACOMBE,DELAHEY,DERRIMUT,DIAMOND CREEK,DIGGERS REST,DIMBOOLA,DINGLEY VILLAGE,DINNER PLAIN,DOCKLANDS,DONCASTER,DONCASTER EAST,DONVALE,DOOKIE,DOREEN,DOVETON,DROMANA,DROUIN,DRUMCONDRA,DRY DIGGINGS,DRYSDALE,DUNNSTOWN,EAGLE POINT,EAGLEHAWK,EAGLEMONT,EAST GEELONG,EAST MELBOURNE,EAST WARBURTON,EBDEN,ECHUCA,ECHUCA WEST,EDITHVALE,EILDON,ELLIMINYT,ELMHURST,ELPHINSTONE,ELSTERNWICK,ELTHAM,ELTHAM NORTH,ELWOOD,EMERALD,ENDEAVOUR HILLS,EPPING,EPSOM,ERICA,ESSENDON,ESSENDON NORTH,ESSENDON WEST,EUMEMMERRING,FAIRFIELD,FAWKNER,FERNTREE GULLY,FERNY CREEK,FITZROY,FITZROY NORTH,FLEMINGTON,FLINDERS,FLORA HILL,FLOWERDALE,FOOTSCRAY,FOOTSCRAY WEST,FOREST HILL,FOSTER,FRANKSTON,FRANKSTON NORTH,FRANKSTON SOUTH,FREEBURGH,FULHAM,GARDENVALE,GARFIELD,GARFIELD NORTH,GEELONG,GEELONG EAST,GEELONG WEST,GEMBROOK,GISBORNE,GLADSTONE PARK,GLEN ALVIE,GLEN HUNTLY,GLEN IRIS,GLEN WAVERLEY,GLENGARRY,GLENLYON,GLENROWAN,GLENROY,GOLDEN POINT,GOLDEN SQUARE,GOWANBRAE,GREAT WESTERN,GREENSBOROUGH,GREENVALE,GROVEDALE,HADDON,HADFIELD,HALLAM,HALLS GAP,HAMILTON,HAMLYN HEIGHTS,HAMPTON,HAMPTON EAST,HAMPTON PARK,HARCOURT,HARRIETVILLE,HASTINGS,HAWTHORN,HAWTHORN EAST,HEALESVILLE,HEALESVILLE MAIN STREET,HEATHCOTE,HEATHCOTE JUNCTION,HEATHERTON,HEATHMONT,HEIDELBERG,HEIDELBERG HEIGHTS,HEIDELBERG WEST,HEPBURN SPRINGS,HERNE HILL,HEYWOOD,HIGHETT,HIGHTON,HILL END,HILLSIDE,HOPPERS CROSSING,HORSHAM,HUGHESDALE,HUNTINGDALE,HUNTLY,HURSTBRIDGE,ICY CREEK,INVERLEIGH,INVERLOCH,INVERMAY,INVERMAY PARK,IRONBARK,IRREWILLIPE,IRYMPLE,IVANHOE,IVANHOE EAST,IVANHOE NORTH,JACANA,JAN JUC,JEPARIT,JOEL JOEL,JOHNSONVILLE,JUNCTION VILLAGE,JUNORTOUN,KALLISTA,KALORAMA,KANGAROO FLAT,KANGAROO GROUND,KANIVA,KARINGAL,KATANDRA WEST,KATUNGA,KAWARREN,KEALBA,KEILOR,KEILOR DOWNS,KEILOR EAST,KEILOR PARK,KENNINGTON,KENSINGTON,KERANG,KEW,KEW EAST,KEYSBOROUGH,KIALLA,KIALLA LAKES,KILLARA,KILMORE,KILMORE EAST,KILSYTH,KILSYTH SOUTH,KINGLAKE,KINGLAKE WEST,KINGS PARK,KINGSBURY,KINGSVILLE,KNOXFIELD,KONGWAK,KOO WEE RUP,KOONDROOK,KOONOOMOO,KOOYONG,KORUMBURRA,KORWEINGUBOORA,KURUNJANG,KYNETON,LAHARUM,LAKE GARDENS,LAKE WENDOUREE,LAKES ENTRANCE,LALOR,LANGWARRIN,LARA,LAUNCHING PLACE,LAURISTON,LAVERTON,LEARMONTH,LEONGATHA,LEOPOLD,LETHBRIDGE,LILYDALE,LITTLE RIVER,LOCH,LOCH SPORT,LOCKWOOD SOUTH,LONG GULLY,LONGFORD,LONGWARRY,LORNE,LOVELY BANKS,LOWER NORTON,LOWER PLENTY,LYNBROOK,LYNDHURST,LYSTERFIELD,MACEDON,MACLEOD,MACS COVE,MAGPIE,MAIDEN GULLY,MAIDSTONE,MAIN RIDGE,MALDON,MALMSBURY,MALVERN,MALVERN EAST,MANDURANG,MANIFOLD HEIGHTS,MANSFIELD,MARIBYRNONG,MARONG,MARYBOROUGH,MARYKNOLL,MARYSVILLE,MCCRAE,MCKINNON,MEADOW HEIGHTS,MELBOURNE,MELTON,MELTON SOUTH,MELTON WEST,MENTONE,MERBEIN,MEREDITH,MERLYNSTON,MERNDA,MERRIJIG,METUNG,MIA MIA,MIDDLE PARK,MILDURA,MILDURA SOUTH,MILDURA WEST,MILL PARK,MILLGROVE,MIRBOO NORTH,MITCHAM,MITCHELL PARK,MOE,MOGGS CREEK,MONBULK,MONT ALBERT,MONT ALBERT NORTH,MONTMORENCY,MONTROSE,MOOLAP,MOONEE PONDS,MOORABBIN,MOOROOLBARK,MOOROOPNA,MORDIALLOC,MORNINGTON,MORTLAKE,MORWELL,MOUNT BEAUTY,MOUNT BULLER,MOUNT CLEAR,MOUNT DANDENONG,MOUNT ELIZA,MOUNT EVELYN,MOUNT FRANKLIN,MOUNT HELEN,MOUNT MACEDON,MOUNT MARTHA,MOUNT PLEASANT,MOUNT WAVERLEY,MULGRAVE,MURCHISON,MURRUMBEENA,MURTOA,MUSK,MYRTLEFORD,NAGAMBIE,NALANGIL,NAR NAR GOON,NAR NAR GOON NORTH,NARINGAL,NARRAWONG,NARRE WARREN,NARRE WARREN NORTH,NARRE WARREN SOUTH,NATHALIA,NEW GISBORNE,NEWBOROUGH,NEWCOMB,NEWHAM,NEWINGTON,NEWLANDS ARM,NEWLYN,NEWPORT,NEWSTEAD,NEWTOWN,NHILL,NIDDRIE,NOBLE PARK,NOBLE PARK NORTH,NORLANE,NORTH BENDIGO,NORTH GEELONG,NORTH MELBOURNE,NORTH SHORE,NORTHCOTE,NOTTING HILL,NUMURKAH,NUNAWADING,OAK PARK,OAKLEIGH,OAKLEIGH EAST,OAKLEIGH SOUTH,OCEAN GROVE,OFFICER,OLINDA,OMEO,ORMOND,OUYEN,OVENS,PAKENHAM,PANTON HILL,PARADISE BEACH,PARK ORCHARDS,PARKDALE,PARKVILLE,PASCOE VALE,PASCOE VALE SOUTH,PATTERSON LAKES,PAYNESVILLE,PEARCEDALE,PETERBOROUGH,PINE LODGE,PIONEER BAY,PLENTY,POINT COOK,POINT LEO,POINT LONSDALE,POREPUNKAH,PORT ALBERT,PORT CAMPBELL,PORT FAIRY,PORT MELBOURNE,PORTARLINGTON,PORTLAND,PORTSEA,POWELLTOWN,PRAHRAN,PRAHRAN EAST,PRESTON,PRESTON WEST,PYRAMID HILL,QUARRY HILL,QUEENSCLIFF,RAINBOW,RAWSON,RED CLIFFS,RED HILL,RED HILL SOUTH,REDAN,REEFTON,REGENT WEST,RESEARCH,RESERVOIR,RICHMOND,RIDDELLS CREEK,RINGWOOD,RINGWOOD EAST,RINGWOOD NORTH,RIPPLESIDE,RIPPONLEA,ROCHESTER,ROCKBANK,ROMSEY,ROSANNA,ROSEBUD,ROSEBUD WEST,ROSS CREEK,ROWVILLE,ROXBURGH PARK,RUPANYUP,RUTHERGLEN,RYE,SAFETY BEACH,SAINT HELENA,SALE,SAN REMO,SANCTUARY LAKES,SANDHURST,SANDRINGHAM,SASSAFRAS,SCORESBY,SEABROOK,SEAFORD,SEAHOLME,SEASPRAY,SEBASTOPOL,SEDDON,SEVILLE,SEYMOUR,SHE OAKS,SHEPPARTON,SHOREHAM,SILVAN,SKIPTON,SKYE,SMEATON,SMITHS BEACH,SOLDIERS HILL,SOMERS,SOMERVILLE,SORRENTO,SOUTH DUDLEY,SOUTH GEELONG,SOUTH MELBOURNE,SOUTH MORANG,SOUTH YARRA,SOUTHBANK,SPOTSWOOD,SPRING GULLY,SPRING HILL,SPRINGVALE,SPRINGVALE SOUTH,ST ALBANS,ST ALBANS PARK,ST ANDREWS,ST ANDREWS BEACH,ST KILDA,ST KILDA EAST,ST KILDA WEST,ST LEONARDS,STANHOPE,STANLEY,STAWELL,STRADBROKE,STRATHDALE,STRATHDOWNIE,STRATHFIELDSAYE,STRATHMERTON,STRATHMORE,SUNBURY,SUNSET STRIP,SUNSHINE,SUNSHINE NORTH,SUNSHINE WEST,SURF BEACH,SURREY HILLS,SWAN REACH,SYDENHAM,TALBOT,TALLANGATTA,TAMBO UPPER,TANGAMBALANGA,TARNEIT,TARRAWINGEE,TARWIN LOWER,TATURA,TAWONGA SOUTH,TAYLORS HILL,TAYLORS LAKES,TECOMA,TEMPLESTOWE,TEMPLESTOWE LOWER,TENBY POINT,TERANG,THE BASIN,THOMASTOWN,THORNBURY,THORNTON,THREE BRIDGES,TOLMIE,TONGALA,TOORADIN,TOORAK,TOOTGAROOK,TORQUAY,TORRUMBARRY,TRAFALGAR,TRAFALGAR EAST,TRAFALGAR SOUTH,TRARALGON,TRARALGON SOUTH,TRAVANCORE,TRENTHAM,TRENTHAM EAST,TRUGANINA,TULLAMARINE,TYABB,TYERS,TYLDEN,UNDERA,UPPER FERNTREE GULLY,UPPER PLENTY,UPWEY,VERMONT,VERMONT SOUTH,VIEWBANK,VIOLET TOWN,WAHGUNYAH,WALLAN,WANDANA HEIGHTS,WANDILIGONG,WANDIN NORTH,WANGANDARY,WANGARATTA,WANTIRNA,WANTIRNA SOUTH,WARBURTON,WARNEET,WARRACKNABEAL,WARRAGUL,WARRANDYTE,WARRNAMBOOL,WATERWAYS,WATSONIA,WATTLE GLEN,WAURN PONDS,WELLSFORD,WELSHMANS REEF,WENDOUREE,WERRIBEE,WERRIBEE SOUTH,WEST FOOTSCRAY,WEST MELBOURNE,WEST WODONGA,WESTBURY,WESTMEADOWS,WHEELERS HILL,WHITE HILLS,WHITTINGTON,WHITTLESEA,WHOROULY,WILDWOOD,WILLIAMSTOWN,WILLOW GROVE,WIMBLEDON HEIGHTS,WINCHELSEA,WINDSOR,WODONGA,WOLLERT,WONGA PARK,WONTHAGGI,WOODEND,WOODSTOCK,WOOLAMAI,WOORI YALLOCK,WUNGHNU,WURRUK,WYNDHAM VALE,YALLAMBIE,YALLOURN NORTH,YARRA GLEN,YARRA JUNCTION,YARRAM,YARRAMBAT,YARRAVILLE,YELLINGBO,YINNAR"];
	[self fillDatabaseByIncludingAustralianList:TRUE forState:@"WA" andSuburbs:@"SHOW ALL,ABBEY,ALBANY,ALEXANDER HEIGHTS,ALFRED COVE,ALLANSON,APPLECROSS,ARDROSS,ARMADALE,ASCOT,ASHBY,ASHFIELD,ATTADALE,ATWELL,AUBIN GROVE,AUGUSTA,AUSTRALIND,AVELEY,BALCATTA,BALDIVIS,BALGA,BALLAJURA,BANKSIA GROVE,BARRAGUP,BASSENDEAN,BATEMAN,BAYNTON,BAYONET HEAD,BAYSWATER,BEACHLANDS,BEACONSFIELD,BECKENHAM,BEDFORD,BEDFORDALE,BEECHBORO,BEELIAR,BELDON,BELMONT,BENTLEY,BERESFORD,BERTRAM,BIBRA LAKE,BICKLEY,BICTON,BINDOON,BINNINGUP,BLUFF POINT,BODDINGTON,BOORAGOON,BOULDER,BOUVARD,BOYA,BOYUP BROOK,BREMER BAY,BRENTWOOD,BRIDGETOWN,BRIGADOON,BROADWATER,BROCKMAN,BROOKDALE,BROOME,BULL CREEK,BULLSBROOK,BUNBURY,BURSWOOD,BUSSELTON,BUTLER,BYFORD,CALISTA,CANNING VALE,CANNINGTON,CAPE BURNEY,CARINE,CARLISLE,CARNARVON,CARRAMAR,CASTLETOWN,CASUARINA,CENTENNIAL PARK,CERVANTES,CHAMPION LAKES,CHIDLOW,CHITTERING,CHRISTMAS ISLAND,CHURCHLANDS,CITY BEACH,CLAREMONT,CLARKSON,CLOVERDALE,COLLIE,COLLINGWOOD PARK,COMO,CONNOLLY,COODANUP,COOGEE,COOLBELLUP,COOLBINIA,COOLGARDIE,COOLOONGUP,COTTESLOE,CRAIGIE,CRANBROOK,CRAWLEY,CURRAMBINE,DAGLISH,DALKEITH,DALYELLUP,DARCH,DARLINGTON,DAWESVILLE,DENMARK,DERBY,DIANELLA,DONNYBROOK,DOUBLEVIEW,DUDLEY PARK,DUNCRAIG,DUNSBOROUGH,DWELLINGUP,EAST CANNINGTON,EAST FREMANTLE,EAST PERTH,EAST VICTORIA PARK,EATON,EDEN HILL,EDGEWATER,ELLENBROOK,EMBLETON,ERSKINE,ESPERANCE,EXMOUTH,FALCON,FERNDALE,FLOREAT,FORRESTDALE,FORRESTFIELD,FREMANTLE,FURNISSDALE,GABBADAH,GELORUP,GERALDTON,GINGIN,GIRRAWHEEN,GLEN FORREST,GLEN IRIS,GLENDALOUGH,GNANGARA,GNOWANGERUP,GOLDEN BAY,GOOSEBERRY HILL,GOSNELLS,GREENFIELDS,GREENMOUNT,GREENWOOD,GWELUP,HALLS HEAD,HAMERSLEY,HAMILTON HILL,HAMMOND PARK,HANNANS,HEATHRIDGE,HELENA VALLEY,HENLEY BROOK,HIGH WYCOMBE,HIGHGATE,HILLARYS,HILLMAN,HILTON,HOCKING,HOPELAND,HUNTINGDALE,ILUKA,INGLEWOOD,INNALOO,JANDAKOT,JANE BROOK,JINDALEE,JOLIMONT,JOONDALUP,JOONDANNA,KALAMUNDA,KALBARRI,KALGAN,KALGOORLIE,KALLAROO,KAMBALDA,KAMBALDA EAST,KARAWARA,KARDINYA,KARRATHA,KARRINYUP,KATANNING,KELMSCOTT,KENSINGTON,KENWICK,KEWDALE,KINGSLEY,KINGSTON,KINROSS,KOJONUP,KOONDOOLA,KOONGAMIA,KUNUNURRA,LAKELANDS,LAMINGTON,LANDSDALE,LANGFORD,LATHLAIN,LEDA,LEDGE POINT,LEEDERVILLE,LEEMAN,LEEMING,LESMURDIE,LOCKRIDGE,LYNWOOD,MADDINGTON,MADELEY,MADORA BAY,MAHOGANY CREEK,MAIDA VALE,MANDURAH,MANJIMUP,MANNING,MARANGAROO,MARGARET RIVER,MARMION,MAYLANDS,MCKAIL,MEADOW SPRINGS,MEDINA,MELVILLE,MENORA,MERREDIN,MERRIWA,MIDDLE SWAN,MIDDLETON BEACH,MIDLAND,MIDVALE,MILLENDON,MINDARIE,MIRA MAR,MIRRABOOKA,MOLLOY ISLAND,MORGANTOWN,MORLEY,MOSMAN PARK,MOUNT BARKER,MOUNT CLAREMONT,MOUNT CLARENCE,MOUNT HAWTHORN,MOUNT HELENA,MOUNT LAWLEY,MOUNT MELVILLE,MOUNT PLEASANT,MOUNT TARCOOLA,MUKINBUDIN,MULLALOO,MUNSTER,MURDOCH,MYAREE,NARROGIN,NEDLANDS,NOLLAMARA,NORANDA,NORTH BEACH,NORTH FREMANTLE,NORTH PERTH,NORTH YUNDERUP,NORTHAM,NORTHBRIDGE,NORTHCLIFFE,O'CONNOR,OCEAN REEF,ORELIA,OSBORNE PARK,PADBURY,PALMYRA,PARKWOOD,PARMELIA,PEARSALL,PELICAN POINT,PERTH,PINJARRA,POINT SAMSON,PORT HEDLAND,PORT KENNEDY,QUEENS PARK,QUINNS ROCKS,RANGEWAY,RAVENSWOOD,REDCLIFFE,RIDGEWOOD,RIVERTON,RIVERVALE,ROCKINGHAM,ROEBOURNE,ROSSMOYNE,SAFETY BAY,SALTER POINT,SAN REMO,SCARBOROUGH,SEABIRD,SECRET HARBOUR,SEVILLE GROVE,SHELLEY,SHENTON PARK,SHOALWATER,SILVER SANDS,SINAGRA,SINGLETON,SORRENTO,SOUTH BUNBURY,SOUTH CARNARVON,SOUTH FREMANTLE,SOUTH GUILDFORD,SOUTH HEDLAND,SOUTH KALGOORLIE,SOUTH LAKE,SOUTH PERTH,SOUTH YUNDERUP,SOUTHERN RIVER,SPEARWOOD,ST JAMES,STIRLING,STRATTON,SUBIACO,SUCCESS,SUNSET BEACH,SWAN VIEW,SWANBOURNE,TAPPING,TARCOOLA BEACH,THE VINES,THORNLIE,THREE SPRINGS,TOODYAY,TRIGG,TUART HILL,TWO ROCKS,USHER,VICTORIA PARK,WAGGRAKINE,WAGIN,WAIKIKI,WANDERING,WANDINA,WANNANUP,WANNEROO,WARNBRO,WAROONA,WARWICK,WATERFORD,WATERMANS BAY,WATTLE GROVE,WEBBERTON,WELLARD,WEMBLEY,WEMBLEY DOWNS,WEST BEACH,WEST LEEDERVILLE,WEST PERTH,WESTFIELD,WESTMINSTER,WHITE GUM VALLEY,WICKHAM,WILLAGEE,WILLETTON,WILSON,WINTHROP,WOODBRIDGE,WOODLANDS,WOODRIDGE,WOODVALE,WORSLEY,WUNDOWIE,WYNDHAM,YALLINGUP,YANCHEP,YANGEBUP,YOKINE"];
}

#pragma mark -
#pragma mark User Database:

// User database (use this for example to store the favorites user places)
// Returns FALSE upon error
- (BOOL)loadUserDatabase:(id)sender
{
	BOOL error = FALSE;
	NSArray *migrations = [NSArray arrayWithObjects:
						   [InitialUserTables migration],
						   nil
						   ];
	
	// to go back for example to remove the applied addtestTablemigration just change andMatchVersion:1
	[FmdbMigrationManager executeForDatabasePath:[self applicationSupportPathForFile:[NSString stringWithFormat:@"appdatabase.sqlite"]] withMigrations:migrations];
	
	self.userdb = [FMDatabase databaseWithPath:[self applicationSupportPathForFile:[NSString stringWithFormat:@"appdatabase.sqlite"]]];
	if (![self.userdb open]) {
		error = TRUE;
	}
	[self.userdb setLogsErrors:TRUE];
	
	return error;
}

// User database (use this for example to store the favorites user places)
// Returns FALSE upon error
- (BOOL)loadUserDatabaseForState:(NSString *)stateName
{
	BOOL error = FALSE;
	NSArray *migrations = [NSArray arrayWithObjects:
						   [InitialUserTables migration],
						   nil
						   ];
	
	// to go back for example to remove the applied addtestTablemigration just change andMatchVersion:1
	[FmdbMigrationManager executeForDatabasePath:[self applicationSupportPathForFile:[NSString stringWithFormat:@"%@_appdatabase.sqlite", stateName]] withMigrations:migrations];
	
	self.userdb = [FMDatabase databaseWithPath:[self applicationSupportPathForFile:[NSString stringWithFormat:@"%@_appdatabase.sqlite", stateName]]];
	if (![self.userdb open]) {
		error = TRUE;
	}
	[self.userdb setLogsErrors:TRUE];
	
	return error;
}

- (void)fillDatabaseByIncludingAustralianList:(BOOL)includeList forState:(NSString *)stateName andSuburbs:(NSString *)suburbs
{
	//[self loadUserDatabaseForState:stateName];
	
	// Suburbs with coordinates
	if (includeList) {
		NSString *aString = [[NSString alloc]initWithContentsOfFile:[self bundlePathForRessource:@"Australian_Post_Codes" ofType:@"nst"]];
		NSArray *localityArray = [aString componentsSeparatedByString:@"\r\n"];
		for (NSString *row in localityArray) {
			NSArray *rowDetails = [row componentsSeparatedByString:@","];
			if ([rowDetails count] == 5) {
				NSString *postcode = [rowDetails objectAtIndex:0];
				NSString *name = [[rowDetails objectAtIndex:1]capitalizedString];
				NSString *state = [[rowDetails objectAtIndex:2]uppercaseString];
				NSString *latitude = [rowDetails objectAtIndex:3];
				NSString *longitude = [rowDetails objectAtIndex:4];
				// Update database
				// Check if suburb already exist if not create or else update
				NSNumber *suburb_id = [NSNumber numberWithInteger:[self.userdb intForQuery:@"select id from generated_suburbs where name = ? and state = ? and postcode = ?", name, state, postcode]];
				if ([suburb_id integerValue] == 0) {
					[self.userdb executeUpdate:@"insert into generated_suburbs (postcode,name,state,latitude,longitude) values (?,?,?,?,?)", postcode, name, state, latitude, longitude];
					suburb_id = [NSNumber numberWithInteger:[self.userdb lastInsertRowId]];
				} else {
					[self.userdb executeUpdate:@"UPDATE generated_suburbs SET postcode = ? where id = ?", postcode, suburb_id];
					[self.userdb executeUpdate:@"UPDATE generated_suburbs SET name = ? where id = ?", name, suburb_id];
					[self.userdb executeUpdate:@"UPDATE generated_suburbs SET state = ? where id = ?", state, suburb_id];
					[self.userdb executeUpdate:@"UPDATE generated_suburbs SET latitude = ? where id = ?", latitude, suburb_id];
					[self.userdb executeUpdate:@"UPDATE generated_suburbs SET longitude = ? where id = ?", longitude, suburb_id];
				}
			}
		}
	}
	
	NSString *aString = [[NSString alloc]initWithContentsOfFile:[self bundlePathForRessource:[NSString stringWithFormat:@"%@_Localities", stateName] ofType:@"nst"]];
	NSArray *localityArray = [aString componentsSeparatedByString:@"\r\n"];
	for (NSString *row in localityArray) {
		NSArray *rowDetails = [row componentsSeparatedByString:@","];
		if ([rowDetails count] == 5) {
			NSString *postcode = [rowDetails objectAtIndex:0];
			NSString *name = [[rowDetails objectAtIndex:1]capitalizedString];
			NSString *state = [[rowDetails objectAtIndex:2]uppercaseString];
			NSString *latitude = [rowDetails objectAtIndex:3];
			NSString *longitude = [rowDetails objectAtIndex:4];
			// Update database
			// Check if suburb already exist if not create or else update
			NSNumber *suburb_id = [NSNumber numberWithInteger:[self.userdb intForQuery:@"select id from generated_suburbs where name = ? and state = ? and postcode = ?", name, state, postcode]];
			if ([suburb_id integerValue] == 0) {
				[self.userdb executeUpdate:@"insert into generated_suburbs (postcode,name,state,latitude,longitude) values (?,?,?,?,?)", postcode, name, state, latitude, longitude];
				suburb_id = [NSNumber numberWithInteger:[self.userdb lastInsertRowId]];
			} else {
				[self.userdb executeUpdate:@"UPDATE generated_suburbs SET postcode = ? where id = ?", postcode, suburb_id];
				[self.userdb executeUpdate:@"UPDATE generated_suburbs SET name = ? where id = ?", name, suburb_id];
				[self.userdb executeUpdate:@"UPDATE generated_suburbs SET state = ? where id = ?", state, suburb_id];
				[self.userdb executeUpdate:@"UPDATE generated_suburbs SET latitude = ? where id = ?", latitude, suburb_id];
				[self.userdb executeUpdate:@"UPDATE generated_suburbs SET longitude = ? where id = ?", longitude, suburb_id];
			}
		}
	}
	
//	// Streets
//	if (TRUE) {
//		NSString *aString = [[NSString alloc]initWithContentsOfFile:[self bundlePathForRessource:@"QLD_Streets" ofType:@"nst"]];
//		NSArray *streetArray = [aString componentsSeparatedByString:@"\r\n"];
//		for (NSString *row in streetArray) {
//			NSArray *rowDetails = [row componentsSeparatedByString:@","];
//			if ([rowDetails count] == 4) {
//				NSString *name = [[rowDetails objectAtIndex:0]lowercaseString];
//				NSString *suburb = [[rowDetails objectAtIndex:1]lowercaseString];
//				NSString *latitude = [rowDetails objectAtIndex:2];
//				NSString *longitude = [rowDetails objectAtIndex:3];
//				// Update database
//				// Check if suburb already exist if not create or else update
//				NSNumber *street_id = [NSNumber numberWithInteger:[self.userdb intForQuery:@"select id from streets where name = ? and suburb = ?", name, suburb]];
//				if ([street_id integerValue] == 0) {
//					[self.userdb executeUpdate:@"insert into streets (name,suburb,latitude,longitude) values (?,?,?,?)", name, suburb, latitude, longitude];
//					street_id = [NSNumber numberWithInteger:[self.userdb lastInsertRowId]];
//				} else {
//					[self.userdb executeUpdate:@"UPDATE streets SET name = ? where id = ?", name, street_id];
//					[self.userdb executeUpdate:@"UPDATE streets SET suburb = ? where id = ?", suburb, street_id];
//					[self.userdb executeUpdate:@"UPDATE streets SET latitude = ? where id = ?", latitude, street_id];
//					[self.userdb executeUpdate:@"UPDATE streets SET longitude = ? where id = ?", longitude, street_id];
//				}
//			}
//		}
//	}
	
	
	// Realestate suburbs
	NSArray *suburbsList = [suburbs componentsSeparatedByString:@","];
	for (NSString *name in suburbsList) {
		// get coordinates for suburb name
		name = [name capitalizedString];
		NSString *latitude = nil;
		NSString *longitude = nil;
		NSString *postcode = nil;
		NSString *state = stateName;
		FMResultSet *rs = [self.userdb executeQuery:@"select postcode,latitude,longitude from generated_suburbs where state = ? and name = ?", state, name];
		if ([rs next]) {
			postcode = [rs stringForColumn:@"postcode"];
			latitude = [rs stringForColumn:@"latitude"];
			longitude = [rs stringForColumn:@"longitude"];
		} else {
			NSLog(@"missed suburb name: %@ for state name: %@", name, stateName);
			
			sleep(3);
			
			// Use google api
			if (![name isEqualToString:@"Show All"]) {
				NSString *urlString = [self urlEncodeValue:[NSString stringWithFormat:@"http://maps.google.com/maps/geo?q=%@,%@&output=json&key=ABQIAAAA4yFxsxoDDepDo3ro17yA1hTjOjqphGs0Y9m3nFH3QZboM8-tuxRd5uNAoXEI-bEFHhLbT33JcyYACA", name, state]];
				NSData *responseData = [NSData dataWithContentsOfURL:[NSURL URLWithString:urlString]];
				
				if ([responseData length] != 0)  {
					NSString *jsonString = [[NSString alloc]initWithData:responseData encoding:NSUTF8StringEncoding];
					SBJSON *json = [[SBJSON alloc]init]; 
					NSDictionary* result = (NSDictionary *)[json objectWithString:jsonString error:nil];
					
					NSArray *placemarks = [result valueForKey:@"Placemark"];
					if (placemarks && [placemarks count] > 0) {
						NSDictionary *placemark = [placemarks objectAtIndex:0];
					
						NSArray *coordinates = [placemark valueForKeyPath:@"Point.coordinates"];
						if (coordinates && [coordinates count] > 1) {
							latitude = [NSString stringWithFormat:@"%@", [coordinates objectAtIndex:1]];
							longitude = [NSString stringWithFormat:@"%@", [coordinates objectAtIndex:0]];
							NSLog(@"google map api found suburb name: %@ for state name: %@", name, stateName);
						}
						
					}
					[jsonString release];
					[json release];
				}
			}
		}
		[rs close];
		
		NSString *fullAddress = nil;
		if (!postcode) {
			fullAddress = [NSString stringWithFormat:@"%@, %@", state,name];
		} else {
			fullAddress = [NSString stringWithFormat:@"%@, %@, %@", state,name,postcode];
		}
		
		// check if suburb already exist if not create
		// Check if suburb already exist if not create or else update
		NSNumber *suburb_id = [NSNumber numberWithInteger:[self.userdb intForQuery:@"select id from suburbs where name = ? and state = ?", name, state]];
		if ([suburb_id integerValue] == 0) {
			[self.userdb executeUpdate:@"insert into suburbs (postcode,name,state,latitude,longitude,full_address) values (?,?,?,?,?,?)", postcode, name, state, latitude, longitude, fullAddress];
			suburb_id = [NSNumber numberWithInteger:[self.userdb lastInsertRowId]];
		} else {
			[self.userdb executeUpdate:@"UPDATE suburbs SET postcode = ? where id = ?", postcode, suburb_id];
			[self.userdb executeUpdate:@"UPDATE suburbs SET name = ? where id = ?", name, suburb_id];
			[self.userdb executeUpdate:@"UPDATE suburbs SET state = ? where id = ?", state, suburb_id];
			[self.userdb executeUpdate:@"UPDATE suburbs SET latitude = ? where id = ?", latitude, suburb_id];
			[self.userdb executeUpdate:@"UPDATE suburbs SET longitude = ? where id = ?", longitude, suburb_id];
			[self.userdb executeUpdate:@"UPDATE suburbs SET full_address = ? where id = ?", fullAddress, suburb_id];
		}
	}
}

- (NSString *)urlEncodeValue:(NSString *)string
{
	CFStringRef originalURLString = (CFStringRef)string;
	CFStringRef preprocessedString = CFURLCreateStringByAddingPercentEscapes(NULL, originalURLString, NULL, (CFStringRef)@"", kCFStringEncodingUTF8);
	//CFStringRef urlString = CFURLCreateStringByAddingPercentEscapes(kCFAllocatorDefault, preprocessedString, NULL, (CFStringRef)@";/?:@&=+$", kCFStringEncodingUTF8);
	NSString *stringToReturn = [NSString stringWithString:(NSString *)preprocessedString];
	CFRelease(preprocessedString);
	return stringToReturn;
}

#pragma mark -
#pragma mark Utilities method to help find ressources from the applications directory or from the user directory:

// Permits to retrieve the path for the given file on the user documents dir
- (NSString *)documentPathForFile:(NSString *)aPath
{
	NSArray *paths = NSSearchPathForDirectoriesInDomains(NSDocumentDirectory, NSUserDomainMask, YES);
	NSString *documentsDirectory = [paths objectAtIndex:0];
	NSString *appFile = [documentsDirectory stringByAppendingPathComponent:aPath];
	return appFile;
}

// Permits to retrieve the path for the given file on the user application support dir
- (NSString *)applicationSupportPathForFile:(NSString *)aPath
{
	
    NSFileManager *fileManager;
    
    fileManager = [NSFileManager defaultManager];
	
	
	
	NSArray *paths = NSSearchPathForDirectoriesInDomains(NSApplicationSupportDirectory, NSUserDomainMask, YES);
	NSString *supportsDirectory = [([paths count] > 0) ? [paths objectAtIndex:0] : NSTemporaryDirectory() stringByAppendingPathComponent:@"AppDatabaseGenerator"];
	
	if ( ![fileManager fileExistsAtPath:supportsDirectory isDirectory:NULL] ) {
        [fileManager createDirectoryAtPath:supportsDirectory attributes:nil];
    }
	
	NSString *appFile = [supportsDirectory stringByAppendingPathComponent:aPath];
	return appFile;
}

// Permits to retrive the path for the given file on the application ressources dir
- (NSString *)bundlePathForRessource:(NSString *)aRessource ofType:(NSString *)aType
{
	NSBundle *bundle = [NSBundle mainBundle];
	NSString *path = [bundle pathForResource:aRessource ofType:aType];
	return path;
}

- (void)dealloc
{
	[_userdb release];
	
	[super dealloc];
}

@end
